# Generated by Django 4.2.3 on 2023-07-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=250)),
                ('emailId', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=250)),
                ('password2', models.CharField(max_length=250)),
                ('apiKey', models.CharField(max_length=1000)),
            ],
        ),
    ]
