# Generated by Django 4.2.3 on 2023-07-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_formdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='apiKey',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
