# Generated by Django 4.2.3 on 2023-07-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_formdata_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='emailId',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
