# Generated by Django 4.2.3 on 2023-07-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_formdata_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
