# Generated by Django 4.2.5 on 2023-09-11 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_formdata_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='apiKey',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='apiKey',
        ),
    ]
